#!/usr/bin/env bash
# Run Nginx as nginx user

# Update the user from www-data to nginx in nginx.conf
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Change the listening port from 80 to 8080 in the default site configuration
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Ensure the nginx.conf file has appropriate permissions
sudo chmod 644 /etc/nginx/nginx.conf

# Restart Nginx service as the nginx user
sudo service nginx restart
