#!/usr/bin/env bash
# Script to install Nginx and configure it to redirect /redirect_me to another page.

# Update package list and install Nginx
sudo apt update -y && sudo apt upgrade -y
sudo apt install nginx -y

# Ensure the correct document root directory exists
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html

# Store configuration content
new_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
"

# Write configuration to Nginx
echo "$new_config" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Test Nginx configuration for errors
sudo nginx -t

# Reload Nginx to apply changes
sudo systemctl reload nginx
